import mumaker from 'mumaker';

const TEXT_TYPES = {
  metallic: "https://en.ephoto360.com/impressive-decorative-3d-metal-text-effect-798.html",
  ice: "https://en.ephoto360.com/ice-text-effect-online-101.html",
  snow: "https://en.ephoto360.com/create-a-snow-3d-text-effect-free-online-621.html",
  impressive: "https://en.ephoto360.com/create-3d-colorful-paint-text-effect-online-801.html",
  matrix: "https://en.ephoto360.com/matrix-text-effect-154.html",
  light: "https://en.ephoto360.com/light-text-effect-futuristic-technology-style-648.html",
  neon: "https://en.ephoto360.com/create-colorful-neon-light-text-effects-online-797.html",
  devil: "https://en.ephoto360.com/neon-devil-wings-text-effect-online-683.html",
  purple: "https://en.ephoto360.com/purple-text-effect-online-100.html",
  thunder: "https://en.ephoto360.com/thunder-text-effect-online-97.html",
  leaves: "https://en.ephoto360.com/green-brush-text-effect-typography-maker-online-153.html",
  arena: "https://en.ephoto360.com/create-cover-arena-of-valor-by-mastering-360.html",
  hacker: "https://en.ephoto360.com/create-anonymous-hacker-avatars-cyan-neon-677.html",
  sand: "https://en.ephoto360.com/write-names-and-messages-on-the-sand-online-582.html",
  blackpink: "https://en.ephoto360.com/create-a-blackpink-style-logo-with-members-signatures-810.html",
  glitch: "https://en.ephoto360.com/create-digital-glitch-text-effects-online-767.html",
  fire: "https://en.ephoto360.com/flame-lettering-effect-372.html",
  '1917': "https://en.ephoto360.com/1917-style-text-effect-523.html"
};

const formatTypes = () =>
  Object.keys(TEXT_TYPES).map(t => `• ${t}`).join('\n');

export default {
  name: 'textmaker',
  alias: ['textgen', 'ephoto', 'tm'],
  category: 'Image',
  description: 'Generates stylish text with different ePhoto360 effects',

  async execute(kaya, m, args) {
    const chatId = m.chat;

    // 🧠 Normalize arguments
    const type = args[0]?.toLowerCase();
    const text = args.slice(1).join(' ').trim();

    // ❌ Incorrect usage
    if (!type || !TEXT_TYPES[type]) {
      return kaya.sendMessage(chatId, {
        text:
`❌ *Incorrect usage of TextMaker*

📌 *Usage*:
.textmaker <type> <text>

🎨 *Available types*:
${formatTypes()}

✨ *Example*:
.textmaker metallic Kaya`
      }, { quoted: m });
    }

    // ❌ Missing text
    if (!text) {
      return kaya.sendMessage(chatId, {
        text:
`❌ *Missing text*

📌 Example:
.textmaker ${type} Kaya`
      }, { quoted: m });
    }

    try {
      const result = await mumaker.ephoto(TEXT_TYPES[type], text);

      if (!result?.image) throw new Error('Image not generated');

      await kaya.sendMessage(chatId, {
        image: { url: result.image },
        caption: '✨ *GENERATED BY KAYA-MD* ✨'
      }, { quoted: m });

    } catch (err) {
      console.error('❌ textmaker error:', err);
      await kaya.sendMessage(chatId, {
        text: `❌ Unable to generate image.\nError: ${err.message}`
      }, { quoted: m });
    }
  }
};